# Generated by Django 3.1.5 on 2021-01-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_body', models.CharField(max_length=32, verbose_name='tapki tesak')),
            ],
            options={
                'verbose_name': 'Թափքի տեսակ',
                'verbose_name_plural': 'Թափքի տեսակ',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Մակնիշ',
                'verbose_name_plural': 'Մակնիշ',
            },
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Մաքսազերծված է',
                'verbose_name_plural': 'Մաքսազերծված է',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Գույն',
                'verbose_name_plural': 'Գույն',
            },
        ),
        migrations.CreateModel(
            name='DriveUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_unit', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Քարշակ',
                'verbose_name_plural': 'Քարշակ',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Վառելիք',
                'verbose_name_plural': 'Վառելիք',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_country', models.CharField(max_length=30, verbose_name='Manufacturer country')),
            ],
            options={
                'verbose_name': 'Արտադրման երկիր',
                'verbose_name_plural': 'Արտադրման երկիր',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Շարժիչի ծավալ',
                'verbose_name_plural': 'Շարժիչի ծավալ',
            },
        ),
        migrations.CreateModel(
            name='ProductYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_year', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Տարի',
                'verbose_name_plural': 'Տարի',
            },
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Տարածաշրջան',
                'verbose_name_plural': 'Տարածաշրջան',
            },
        ),
        migrations.CreateModel(
            name='Steering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steering', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Ղեկ',
                'verbose_name_plural': 'Ղեկ',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Փոխանցման տուփ',
                'verbose_name_plural': 'Փոխանցման տուփ',
            },
        ),
        migrations.CreateModel(
            name='RegionChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_child', models.CharField(max_length=55, verbose_name='Поселение')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.regionmodel', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Տարածաշրջան-Raion',
                'verbose_name_plural': 'Տարածաշրջան-Raion',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, verbose_name='MOdel name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.carbrand')),
            ],
            options={
                'verbose_name': 'Մոդել',
                'verbose_name_plural': 'Մոդել',
            },
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('show_vin_code', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=False, verbose_name='Նոր')),
                ('used', models.BooleanField(default=False, verbose_name='Օգտագործված')),
                ('horse_power', models.IntegerField(verbose_name='Ձիաուժ')),
                ('millage_int', models.IntegerField(verbose_name='Վազք')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Գին')),
                ('photo_main', models.ImageField(upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('mileage', models.CharField(choices=[('ARM', 'Am'), ('RUS', 'Ru'), ('EN', 'En')], default='ARM', max_length=50)),
                ('description', models.TextField(verbose_name='Նկարագրել')),
                ('hashtag', models.CharField(blank=True, max_length=255, verbose_name='Գաղտնի որոնում')),
                ('contact', models.CharField(max_length=33, verbose_name='Կոնտակտ')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('zangi', 'Zangi')], max_length=32, verbose_name='Կոնտակտ_type')),
                ('exchange', models.BooleanField(default=False, verbose_name='Փոխանակում')),
                ('dealer', models.BooleanField(default=False, verbose_name='Դիլլեր')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='don`t tuch)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.carbrand')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.carbody')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.carmodel')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.clearance')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.color')),
                ('drive_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.driveunit')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.fuel')),
                ('man_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.manufacturercountry')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.motor')),
                ('product_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport_app.productyear')),
                ('region_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.regionchildmodel')),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.regionmodel')),
                ('steering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.steering')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.transmission')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
        ),
    ]
